[project]
name = "projeto-pesquisa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fitz>=0.0.1.dev2",
    "google-genai>=1.67.0",

    "pandas>=3.0.1",
    "pdfplumber>=0.11.9",
    "pymupdf>=1.27.2",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
]

